
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-cache_demo}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fersko-redis-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres} -d ${POSTGRES_DATABASE:-cache_demo}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: cache-redis
      dockerfile: Dockerfile
    container_name: fersko-api
    environment:
      POSTGRES_HOST: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE:-cache_demo}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    ports:
      - "${API_PORT}:8080"
    networks:
      - fersko-redis-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - fersko-redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    depends_on:
      - redis
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    volumes:
      - redis-insight-data:/data
    networks:
      - fersko-redis-net

volumes:
  redis-insight-data:
  postgres-data:

networks:
  fersko-redis-net:
    driver: bridge